# -*- coding: utf-8 -*-
"""mathplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uasoWRaUoSQnRJnhrJR_kCqYpYqPXQ73
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

electors_2009 = pd.read_csv("LS2009Electors.csv")
candidate_2009 = pd.read_csv("candidate09.csv")

electors_2009.head()

candidate_2009.head()

candidate_2009.Candidate_Sex.describe()

x = list(candidate_2009.Candidate_Sex.unique())
y = list(candidate_2009.Candidate_Sex.value_counts())
plt.xlabel("Gender")
plt.ylabel("Count")
plt.bar(x,y)
plt.show()



